export const BRAND_COLORS = {
  // ── US Ivies & top liberal arts ──
  'Harvard University':                      '#A51C30',
  'Yale University':                         '#00356B',
  'Princeton University':                    '#E77500',
  'Columbia University':                     '#003DA5',
  'University of Pennsylvania':              '#011F5B',
  'Cornell University':                      '#B31B1B',
  'Dartmouth College':                       '#00693E',
  'Brown University':                        '#4E3629',
  'Massachusetts Institute of Technology':   '#A31F34',
  'Caltech':                                 '#FF6C0C',
  'Stanford University':                     '#8C1515',
  'Duke University':                         '#003087',
  'Johns Hopkins University':                '#002D72',
  'Carnegie Mellon University':              '#C0392B',
  'Northwestern University':                 '#4E2A84',
  'University of Chicago':                   '#800000',
  'University of Notre Dame':                '#0C2340',
  'Georgetown University':                   '#002D6D',
  'Vanderbilt University':                   '#866D4B',
  'Rice University':                         '#00205B',
  'Tufts University':                        '#417BD5',
  'Emory University':                        '#012169',
  'University of Virginia':                  '#232D4B',
  'Washington University in St. Louis':      '#A51417',
  'Wake Forest University':                  '#9E7E38',
  'Tulane University':                       '#006747',
  'University of Southern California':       '#990000',
  'New York University':                     '#57068C',
  'NYU Abu Dhabi':                           '#57068C',
  'Boston University':                       '#CC0000',
  'Boston College':                          '#8A0029',
  'Northeastern University':                 '#C8102E',
  'Lehigh University':                       '#6B3529',
  'Case Western Reserve University':         '#0A3161',
  'Syracuse University':                     '#F76900',
  'Fordham University':                      '#6B1E3C',
  'Villanova University':                    '#003366',
  'Rutgers University':                      '#CC0033',
  'Temple University':                       '#9D2235',
  'Drexel University':                       '#07294D',
  'George Washington University':            '#002E5D',
  'American University':                     '#003F87',
  'Indiana University Bloomington':          '#990000',
  'Purdue University':                       '#8E6F3E',
  'Michigan State University':               '#18453B',
  'Ohio State University':                   '#BB0000',
  'University of Michigan':                  '#003FA5',
  'University of Wisconsin-Madison':         '#C5050C',
  'University of Washington':                '#4B2E83',
  'University of North Carolina':            '#4B9CD3',
  'University of Texas at Austin':           '#BF5700',
  'University of Florida':                   '#FA4616',
  'Penn State University':                   '#001E44',
  'Virginia Tech':                           '#861F41',
  'University of Maryland':                  '#E03A3E',
  'Georgia Institute of Technology':         '#B3861B',
  'University of Illinois Urbana-Champaign': '#E84A27',
  'University of Minnesota':                 '#7A0019',
  'University of Colorado Boulder':          '#CFB87C',
  'University of Arizona':                   '#AB0520',
  'Arizona State University':                '#8C1D40',
  // Liberal arts
  'Williams College':                        '#512888',
  'Amherst College':                         '#3F1F69',
  'Swarthmore College':                      '#6B0005',
  'Wellesley College':                       '#003B8C',
  'Middlebury College':                      '#1E427F',
  'Bowdoin College':                         '#003580',
  'Carleton College':                        '#003082',
  'Colgate University':                      '#820000',
  'Colby College':                           '#003893',
  'Hamilton College':                        '#003366',
  'Grinnell College':                        '#BE0000',
  'Davidson College':                        '#CC0000',
  'Harvey Mudd College':                     '#F05A28',
  'Claremont McKenna College':               '#C5962C',
  'Pomona College':                          '#004B8E',
  'Haverford College':                       '#C0001D',
  'Vassar College':                          '#721232',
  'Barnard College':                         '#003DA5',
  'Spelman College':                         '#004B87',
  'Howard University':                       '#003082',
  'Morehouse College':                       '#002868',
  'Babson College':                          '#004080',
  'Olin College of Engineering':             '#005CB4',
  'Cooper Union':                            '#231F20',
  // ── UK & Ireland ──
  'University of Oxford':                    '#002147',
  'University of Cambridge':                 '#003B5C',
  'Imperial College London':                 '#003E74',
  'London School of Economics':              '#BA0225',
  'University College London':               '#500778',
  "King's College London":                   '#750038',
  'University of Edinburgh':                 '#00325F',
  'University of Manchester':                '#660099',
  'University of Bristol':                   '#003B5C',
  'Durham University':                       '#7D2239',
  'University of Warwick':                   '#762A4F',
  'University of Glasgow':                   '#003865',
  'University of Birmingham':                '#2B0D61',
  'University of Leeds':                     '#003377',
  'University of St Andrews':                '#003162',
  'Heriot-Watt University':                  '#0D2B56',
  'University of Exeter':                    '#002147',
  'University of Bath':                      '#1D3C6E',
  'University of Nottingham':                '#005694',
  'Lancaster University':                    '#C9122A',
  'Loughborough University':                 '#7A0019',
  'Queen Mary University of London':         '#002781',
  'University of Sheffield':                 '#002147',
  'University of Southampton':               '#003B5C',
  'University of York':                      '#1E3E6E',
  'University of Aberdeen':                  '#003366',
  'Trinity College Dublin':                  '#012169',
  'University College Dublin':               '#003478',
  // ── Europe ──
  'ETH Zurich':                              '#1F407A',
  'EPFL':                                    '#E00026',
  'Sciences Po':                             '#C7001E',
  'HEC Paris':                               '#0C1B4D',
  'Bocconi University':                      '#003366',
  'TU Delft':                                '#00A6D6',
  'KU Leuven':                               '#003082',
  'University of Amsterdam':                 '#BB0000',
  'Leiden University':                       '#001158',
  'Technical University of Munich':          '#0073A5',
  'Ludwig Maximilian University':            '#009FE3',
  'RWTH Aachen University':                  '#00549F',
  'Heidelberg University':                   '#C1002A',
  'Maastricht University':                   '#00273D',
  'Lund University':                         '#A5303B',
  'Uppsala University':                      '#990000',
  'University of Copenhagen':                '#901A1E',
  'KTH Royal Institute of Technology':       '#003366',
  'Aalto University':                        '#FFBE00',
  'École Polytechnique':                     '#003399',
  'École Normale Supérieure':                '#002A5C',
  'Sorbonne University':                     '#00308F',
  'University of Bologna':                   '#CC0000',
  'Politecnico di Milano':                   '#FFCC00',
  // ── Asia-Pacific ──
  'National University of Singapore':        '#003D7C',
  'Nanyang Technological University':        '#C8102E',
  'Singapore Management University':         '#00205B',
  'KAIST':                                   '#003C71',
  'Seoul National University':               '#0039A6',
  'Yonsei University':                       '#003087',
  'Korea University':                        '#C8102E',
  'POSTECH':                                 '#0B3083',
  'University of Tokyo':                     '#004098',
  'Kyoto University':                        '#663300',
  'Tohoku University':                       '#003087',
  'Osaka University':                        '#003087',
  'Tokyo Institute of Technology':           '#004098',
  'Keio University':                         '#990033',
  'Tsinghua University':                     '#660874',
  'Peking University':                       '#410099',
  'Fudan University':                        '#990000',
  'Shanghai Jiao Tong University':           '#B8191A',
  'Nanjing University':                      '#003087',
  'Hong Kong University of Science and Technology': '#003087',
  'University of Hong Kong':                 '#003366',
  'Chinese University of Hong Kong':         '#65005B',
  'Australian National University':          '#374EA2',
  'University of Melbourne':                 '#000C3D',
  'University of Sydney':                    '#00003E',
  'University of New South Wales':           '#FFD100',
  'Monash University':                       '#006DAE',
  // ── Canada ──
  'University of Toronto':                   '#002A5C',
  'McGill University':                       '#ED1B2F',
  'University of British Columbia':          '#002145',
  'University of Waterloo':                  '#8B6914',
  'McMaster University':                     '#7A003C',
  "Queen's University":                      '#002452',
  'University of Alberta':                   '#007C41',
  'Simon Fraser University':                 '#CC0000',
  'University of Calgary':                   '#C8102E',
  'Dalhousie University':                    '#FACC1B',
  'Western University':                      '#4F2683',
  // ── Middle East / Africa ──
  'MBZUAI':                                  '#00A0E9',
  'Khalifa University':                      '#003087',
  'American University of Beirut':           '#003DA5',
  'American University in Cairo':            '#003087',
  'American University of Sharjah':          '#003087',
  'Sabanci University':                      '#0072C6',
  'Koç University':                          '#002B5C',
  'Bilkent University':                      '#C8102E',
  'Boğaziçi University':                     '#4169E1',
  'Hebrew University of Jerusalem':          '#003DA5',
  'Tel Aviv University':                     '#003087',
  'Technion - Israel Institute of Technology': '#003087',
  // ── South Asia ──
  'IIT Bombay':                              '#003087',
  'IIT Delhi':                               '#003087',
  'IIT Madras':                              '#003087',
  'IIT Kanpur':                              '#003087',
  'IIT Kharagpur':                           '#003087',
  'Indian Institute of Science':             '#002D72',
  'BITS Pilani':                             '#0066CC',
  'Ashoka University':                       '#FF6B00',
  'Lahore University of Management Sciences':'#003087',
  // ── Misc ──
  'Minerva University':                      '#2D2D8F',
  'Yale-NUS College':                        '#00356B',
};

const FALLBACK_HUES = ['#6366F1','#0EA5E9','#10B981','#F59E0B','#EC4899','#8B5CF6','#EF4444','#14B8A6'];

export function getBrandColor(uni) {
  if (!uni) return '#1273C4'; // Common App blue
  const known = BRAND_COLORS[uni.name];
  if (known) return known;
  let h = 0;
  for (let i = 0; i < (uni.name || '').length; i++) h = (h * 31 + uni.name.charCodeAt(i)) & 0xffffffff;
  return FALLBACK_HUES[Math.abs(h) % FALLBACK_HUES.length];
}

export function hexToRgb(hex) {
  const h = hex.replace('#', '');
  const n = parseInt(h.length === 3 ? h.split('').map(c => c + c).join('') : h, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

export function essayCardStyle(uni, isActive) {
  const color = getBrandColor(uni);
  const [r, g, b] = hexToRgb(color);
  return {
    background:  `rgba(${r},${g},${b},${isActive ? 0.08 : 0.05})`,
    borderColor: `rgba(${r},${g},${b},${isActive ? 0.45 : 0.22})`,
    boxShadow:   isActive
      ? `0 4px 14px rgba(${r},${g},${b},0.22)`
      : `0 2px 8px rgba(${r},${g},${b},0.10)`,
    _color: color,
  };
}

export function overviewCardStyle(uni) {
  const color = getBrandColor(uni);
  const [r, g, b] = hexToRgb(color);
  return {
    background:  `rgba(${r},${g},${b},0.10)`,
    borderColor: `rgba(${r},${g},${b},0.28)`,
    boxShadow:   `0 3px 0 rgba(${r},${g},${b},0.35)`,
    uniColor:    color,
  };
}
